name: flutter_bluetooth_basic_example
description: Demonstrates how to use the flutter_bluetooth_basic plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_basic:
    path: ../

flutter:
  uses-material-design: true
