name: flutter_bluetooth_basic
description: Flutter plugin that allows to find bluetooth devices & send raw bytes data
version: 2.0.1
homepage: https://github.com/andrey-ushakov/flutter_bluetooth_basic

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  rxdart: ^0.26.0
  permission_handler: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.tablemi.flutter_bluetooth_basic
        pluginClass: FlutterBluetoothBasicPlugin
      ios:
        pluginClass: FlutterBluetoothBasicPlugin
